version: "2"
services:
  ########## APPLICATIONS ##########
  send:
    profiles:
      - local
    build:
      context: ../send/
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    environment:
      APP_ENV: docker
    volumes:
      - ../send/src:/usr/src/send/src
    depends_on:
      - redis
      - kafka-init

  consume:
    profiles:
      - local
    build:
      context: ../consume/
      dockerfile: Dockerfile.local
    environment:
      APP_ENV: docker
    volumes:
      - ../consume/src:/usr/src/consume/src
    depends_on:
      - redis
      - kafka-init

  ########## INFRASTRUCTURE ##########
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    profiles:
      - infra
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    profiles:
      - infra
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-init:
    image: confluentinc/cp-kafka:latest
    profiles:
      - infra
    depends_on:
      - kafka
    command:
      - /bin/sh
      - -c
      - |
        kafka-topics --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic messages

  redis:
    image: redis
    profiles:
      - infra
    ports:
      - "6379:6379"

  ########## DEVTOOLS ##########
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    profiles:
      - devtools
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
